# This is a basic workflow to help you get started with Actions

name: CMS purge github theme cache

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # checkout the private repo containing the action to run
      - name: Checkout GitHub Action Repo
        uses: actions/checkout@v2
        with:
          repository: dwebcomexposium/CR7EzCache
          ref: refs/heads/master
          token: ${{ secrets.TOKEN_CR7 }} # stored in GitHub secrets
          path: .github/actions/CR7
      - name: Purge CMS github cache
        uses: ./.github/actions/CR7
        with:
          url: https://www.cms-cxpm.com/Themes-git/SIAL-2019-desktop
          url2: https://www.cms-cxpm.com/Themes-git/SIAL-2019-mobile
        env:
          CMS_LOG: ${{ secrets.CMS_LOG }} 
          CMS_PASS: ${{ secrets.CMS_PASS }}
